In [34]:
import pandas as pd

# ConfiguraÃ§Ãµes para exibir todas as linhas e colunas
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

# Carregar o arquivo Excel
df = pd.read_excel('./Escala de Yale (respostas) (1).xlsx')

# Colunas a serem removidas
columns_to_drop = [
    "Pontos 1", "Pontos 2", "Pontos 3", "Pontos 4", "Pontos 5", "Pontos 6", 
    "Pontos 7", "Pontos 8", "Pontos 9", "Pontos 10", "Pontos 11", "Pontos 12", 
    "Pontos 13", "Unnamed: 16", "Pontos Totais", "Significado ClÃ­nico", 
    "DiagnÃ³stico", "Unnamed: 20"
]

# Remover as colunas desnecessÃ¡rias
df = df.drop(columns=columns_to_drop)

# Renomear as colunas manualmente
manual_column_names = {
    '1 - Eu comi atÃ© o ponto em que eu me senti fisicamente doente': 'q1',
    '2 - Eu passei muito tempo me sentindo lento ou cansado apÃ³s ter comido em excesso': 'q2',
    '3 - Eu evitei o trabalho, escola ou atividades sociais porque eu tive medo que eu fosse comer demais lÃ¡': 'q3',
    '4 - Se eu estivesse com problemas emocionais porque eu nÃ£o tinha comido certos alimentos, gostaria de comÃª-los para me sentir melhor.': 'q4',
    '5 - O meu comportamento alimentar me causou muito sofrimento': 'q5',
    '6 - Eu tive problemas significativos na minha vida por causa de comida. Podem ter sido problemas com a minha rotina diÃ¡ria, trabalho, escola, amigos, famÃ­lia, ou de saÃºde.': 'q6',
    '7 - Meus excessos com comida me prejudicaram no cuidado da minha famÃ­lia ou com tarefas domÃ©sticas': 'q7',
    '8 - Eu continuei comendo da mesma forma, mesmo este fato tendo me causado problemas emocionais.': 'q8',
    '9 - Comer a mesma quantidade de alimento nÃ£o me deu tanto prazer como costumava me dar': 'q9',
    '10 - Eu tinha impulsos tÃ£o fortes para comer certos alimentos que eu nÃ£o conseguia pensar em mais nada.': 'q10',
    '11 - Eu tentei e nÃ£o consegui reduzir ou parar de comer certos alimentos': 'q11',
    '12 - Eu estava tÃ£o distraÃ­do pela ingestÃ£o que eu poderia ter sido ferido (por exemplo, ao dirigir um carro, atravessando a rua, operando mÃ¡quinas': 'q12',
    '13 - Nos Ãºltimos 12 meses [Meus amigos ou familiares estavam preocupados com o quanto eu comia.': 'q13'
}

# Aplicar os novos nomes Ã s colunas
df.rename(columns=manual_column_names, inplace=True)


# Mapeamento das respostas para valores numÃ©ricos
response_mapping = {
    "Nunca": 0,
    "Menos que mensalmente": 1,
    "Uma vez por mÃªs": 2,
    "2-3 vezes por mÃªs": 3,
    "Uma vez por semana": 4,
    "2-3 vezes por semana": 5,
    "4-6 vezes por semana": 6,
    "Todos os dias": 7
}

# Aplicar o mapeamento em todas as colunas
df.replace(response_mapping, inplace=True)

# Exibir as primeiras linhas do DataFrame normalizado
df.head(15)

/tmp/ipykernel_846/1460086872.py:55: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace(response_mapping, inplace=True)

,Carimbo de data/hora,Identificador do paciente:,q1,q2,q3,q4,q5,q6,q7,q8,q9,q10,q11,q12,q13,Origem do paciente:
0,2022-10-10 14:19:51.026,1,0,1,2,3,4,5,6,7,6,5,4,3,2,NaN
1,2022-10-11 13:39:58.135,11101,5,6,0,0,4,3,0,3,0,0,3,0,2,NaN
2,2022-10-11 14:54:35.152,11102,0,4,0,5,3,5,5,7,5,6,3,0,7,NaN
3,2022-10-14 10:33:38.867,1401,3,3,0,0,1,1,0,1,3,0,0,0,3,NaN
4,2022-11-09 07:35:44.734,36,3,3,0,6,5,3,0,0,0,1,0,7,0,NaN
5,2022-11-30 07:39:57.997,11,0,2,0,0,1,0,0,0,1,0,7,0,0,NaN
6,2022-11-30 07:47:38.796,12,0,3,0,0,2,2,0,1,0,2,0,0,0,NaN
7,2022-11-30 08:10:19.276,33,2,7,0,3,3,1,1,7,2,0,3,0,7,NaN
8,2022-11-30 08:18:21.959,14,2,3,0,2,5,7,7,1,0,0,2,0,2,NaN
9,2022-11-30 08:31:41.985,55,0,2,0,0,0,0,0,0,1,0,0,0,7,NaN
10,2022-11-30 08:45:48.739,56,1,1,0,0,7,7,7,7,1,0,7,0,1,NaN
11,2023-01-17 10:32:38.183,15,5,5,1,3,5,5,0,5,3,4,1,0,1,Rede Privada
12,2023-01-18 15:26:01.097,102,1,1,1,4,5,1,5,5,0,1,7,1,7,Rede Privada
13,2023-02-13 12:29:09.352,1,0,1,0,1,0,0,0,1,0,0,3,0,1,Rede PÃºblica
14,2023-02-14 08:58:02.232,100,4,3,0,2,2,3,1,2,0,0,0,0,0,Rede PÃºblica

In [35]:
import pandas as pd

# ConfiguraÃ§Ãµes para exibir todas as linhas e colunas
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

# Carregar o arquivo Excel
df = pd.read_excel('./Escala de Yale (respostas) (1).xlsx')

# Colunas a serem removidas
columns_to_drop = [
    "Pontos 1", "Pontos 2", "Pontos 3", "Pontos 4", "Pontos 5", "Pontos 6", 
    "Pontos 7", "Pontos 8", "Pontos 9", "Pontos 10", "Pontos 11", "Pontos 12", 
    "Pontos 13", "Unnamed: 16", "Pontos Totais", "Significado ClÃ­nico", 
    "DiagnÃ³stico", "Unnamed: 20"
]

# Remover as colunas desnecessÃ¡rias
df = df.drop(columns=columns_to_drop)

# Renomear as colunas manualmente
manual_column_names = {
    '1 - Eu comi atÃ© o ponto em que eu me senti fisicamente doente': 'q1',
    '2 - Eu passei muito tempo me sentindo lento ou cansado apÃ³s ter comido em excesso': 'q2',
    '3 - Eu evitei o trabalho, escola ou atividades sociais porque eu tive medo que eu fosse comer demais lÃ¡': 'q3',
    '4 - Se eu estivesse com problemas emocionais porque eu nÃ£o tinha comido certos alimentos, gostaria de comÃª-los para me sentir melhor.': 'q4',
    '5 - O meu comportamento alimentar me causou muito sofrimento': 'q5',
    '6 - Eu tive problemas significativos na minha vida por causa de comida. Podem ter sido problemas com a minha rotina diÃ¡ria, trabalho, escola, amigos, famÃ­lia, ou de saÃºde.': 'q6',
    '7 - Meus excessos com comida me prejudicaram no cuidado da minha famÃ­lia ou com tarefas domÃ©sticas': 'q7',
    '8 - Eu continuei comendo da mesma forma, mesmo este fato tendo me causado problemas emocionais.': 'q8',
    '9 - Comer a mesma quantidade de alimento nÃ£o me deu tanto prazer como costumava me dar': 'q9',
    '10 - Eu tinha impulsos tÃ£o fortes para comer certos alimentos que eu nÃ£o conseguia pensar em mais nada.': 'q10',
    '11 - Eu tentei e nÃ£o consegui reduzir ou parar de comer certos alimentos': 'q11',
    '12 - Eu estava tÃ£o distraÃ­do pela ingestÃ£o que eu poderia ter sido ferido (por exemplo, ao dirigir um carro, atravessando a rua, operando mÃ¡quinas': 'q12',
    '13 - Nos Ãºltimos 12 meses [Meus amigos ou familiares estavam preocupados com o quanto eu comia.': 'q13'
}

# Aplicar os novos nomes Ã s colunas
df.rename(columns=manual_column_names, inplace=True)


# Mapeamento das respostas para valores numÃ©ricos
response_mapping = {
    "Nunca": 0,
    "Menos que mensalmente": 1,
    "Uma vez por mÃªs": 2,
    "2-3 vezes por mÃªs": 3,
    "Uma vez por semana": 4,
    "2-3 vezes por semana": 5,
    "4-6 vezes por semana": 6,
    "Todos os dias": 7
}

# Aplicar o mapeamento em todas as colunas
df.replace(response_mapping, inplace=True)

# Exibir as primeiras linhas do DataFrame normalizado
df.head(15)

/tmp/ipykernel_846/1460086872.py:55: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace(response_mapping, inplace=True)

,Carimbo de data/hora,Identificador do paciente:,q1,q2,q3,q4,q5,q6,q7,q8,q9,q10,q11,q12,q13,Origem do paciente:
0,2022-10-10 14:19:51.026,1,0,1,2,3,4,5,6,7,6,5,4,3,2,NaN
1,2022-10-11 13:39:58.135,11101,5,6,0,0,4,3,0,3,0,0,3,0,2,NaN
2,2022-10-11 14:54:35.152,11102,0,4,0,5,3,5,5,7,5,6,3,0,7,NaN
3,2022-10-14 10:33:38.867,1401,3,3,0,0,1,1,0,1,3,0,0,0,3,NaN
4,2022-11-09 07:35:44.734,36,3,3,0,6,5,3,0,0,0,1,0,7,0,NaN
5,2022-11-30 07:39:57.997,11,0,2,0,0,1,0,0,0,1,0,7,0,0,NaN
6,2022-11-30 07:47:38.796,12,0,3,0,0,2,2,0,1,0,2,0,0,0,NaN
7,2022-11-30 08:10:19.276,33,2,7,0,3,3,1,1,7,2,0,3,0,7,NaN
8,2022-11-30 08:18:21.959,14,2,3,0,2,5,7,7,1,0,0,2,0,2,NaN
9,2022-11-30 08:31:41.985,55,0,2,0,0,0,0,0,0,1,0,0,0,7,NaN
10,2022-11-30 08:45:48.739,56,1,1,0,0,7,7,7,7,1,0,7,0,1,NaN
11,2023-01-17 10:32:38.183,15,5,5,1,3,5,5,0,5,3,4,1,0,1,Rede Privada
12,2023-01-18 15:26:01.097,102,1,1,1,4,5,1,5,5,0,1,7,1,7,Rede Privada
13,2023-02-13 12:29:09.352,1,0,1,0,1,0,0,0,1,0,0,3,0,1,Rede PÃºblica
14,2023-02-14 08:58:02.232,100,4,3,0,2,2,3,1,2,0,0,0,0,0,Rede PÃºblica

In [36]:
perguntas = [
    'q1', 'q2', 'q3', 'q4', 'q5', 'q6', 
    'q7', 'q8', 'q9', 'q10', 'q11', 'q12', 'q13'
]

# Definir os valores numÃ©ricos que representam sintomas
frequencias_sintomas_padrao = [5, 6, 7]  # 2-3 vezes por semana, 4-6 vezes por semana, Todos os dias

# Itens especÃ­ficos onde "Uma vez por semana" (valor 4) tambÃ©m conta como sintoma

itens_especiais = ['q1', 'q2', 'q4', 'q9', 'q10', 'q11']

# FunÃ§Ã£o para contar sintomas por paciente com critÃ©rio ajustado
def contar_sintomas(row):
    count = 0
    for pergunta in perguntas:
        if pergunta in itens_especiais:
            # Para itens especiais, "Uma vez por semana" (4) tambÃ©m Ã© considerado sintoma
            if row[pergunta] in frequencias_sintomas_padrao or row[pergunta] == 4:
                count += 1
        else:
            # Para os demais itens, apenas frequÃªncias mais altas sÃ£o consideradas sintomas
            if row[pergunta] in frequencias_sintomas_padrao:
                count += 1
    return count

# Aplicar a funÃ§Ã£o e criar uma nova coluna com a contagem de sintomas
df['Total_Sintomas'] = df.apply(contar_sintomas, axis=1)

# Classificar a severidade
def classificar_severidade(sintomas):
    if sintomas <= 1:
        return "Sem adicÃ§Ã£o"
    elif 2 <= sintomas <= 3:
        return "Leve"
    elif 4 <= sintomas <= 5:
        return "Moderado"
    elif sintomas >= 6:
        return "Grave"

df['Severidade'] = df['Total_Sintomas'].apply(classificar_severidade)

# Contar pacientes em cada classificaÃ§Ã£o
contagem_severidade = df['Severidade'].value_counts()
print(contagem_severidade)

# Percentual de pacientes em cada classificaÃ§Ã£o
percentual_severidade = df['Severidade'].value_counts(normalize=True) * 100
print("\nPercentual:")
print(percentual_severidade)

Severidade
Sem adicÃ§Ã£o    38
Grave          14
Leve           13
Moderado        3
Name: count, dtype: int64

Percentual:
Severidade
Sem adicÃ§Ã£o    55.882353
Grave          20.588235
Leve           19.117647
Moderado        4.411765
Name: proportion, dtype: float64

In [37]:
# Substituir NaN por "N/A" na coluna de origem
# import matplotlib.pyplot as plt
df['Origem do paciente:'] = df['Origem do paciente:'].fillna('N/A')

# Total de registros
total_registros = len(df)
print(f"Total de registros: {total_registros}")

# Contagem por origem do paciente
contagem_por_origem = df.groupby('Origem do paciente:').size()
print("\nContagem por origem do paciente:")
print(contagem_por_origem)

# Percentual por origem
percentual_por_origem = df.groupby('Origem do paciente:').size() / total_registros * 100
print("\nPercentual por origem do paciente:")
print(percentual_por_origem.round(2))

# Cruzamento de severidade com origem
print("\nSeveridade por origem do paciente:")
tabela_cruzada = pd.crosstab(df['Origem do paciente:'], df['Severidade'], normalize='index') * 100
print(tabela_cruzada.round(2))

# tabela_cruzada.plot(kind='bar', stacked=True, figsize=(10, 6), colormap='viridis')

# # ConfiguraÃ§Ãµes do grÃ¡fico
# plt.title('DistribuiÃ§Ã£o de Severidade por Origem do Paciente', fontsize=16)
# plt.xlabel('Origem do Paciente', fontsize=12)
# plt.ylabel('Percentual (%)', fontsize=12)
# plt.legend(title='Severidade', bbox_to_anchor=(1.05, 1), loc='upper left')
# plt.xticks(rotation=45, ha='right')
# plt.tight_layout()

# # Exibir o grÃ¡fico
# plt.show()

Total de registros: 68

Contagem por origem do paciente:
Origem do paciente:
N/A             11
Rede Privada     3
Rede PÃºblica    54
dtype: int64

Percentual por origem do paciente:
Origem do paciente:
N/A             16.18
Rede Privada     4.41
Rede PÃºblica    79.41
dtype: float64

Severidade por origem do paciente:
Severidade            Grave   Leve  Moderado  Sem adicÃ§Ã£o
Origem do paciente:
N/A                   18.18  36.36      9.09        36.36
Rede Privada         100.00   0.00      0.00         0.00
Rede PÃºblica          16.67  16.67      3.70        62.96

In [38]:
# DistribuiÃ§Ã£o da contagem de sintomas
contagem_sintomas = df['Total_Sintomas'].value_counts().sort_index()
print("DistribuiÃ§Ã£o do Total de Sintomas:")
print(contagem_sintomas)

# Percentual de cada contagem de sintomas
percentual_sintomas = df['Total_Sintomas'].value_counts(normalize=True).sort_index() * 100
print("\nPercentual de cada contagem de sintomas:")
print(percentual_sintomas.round(2))

# VisualizaÃ§Ã£o da distribuiÃ§Ã£o com grÃ¡fico (opcional)

DistribuiÃ§Ã£o do Total de Sintomas:
Total_Sintomas
0     29
1      9
2      7
3      6
4      2
5      1
6      4
7      1
8      3
9      1
10     1
12     1
13     3
Name: count, dtype: int64

Percentual de cada contagem de sintomas:
Total_Sintomas
0     42.65
1     13.24
2     10.29
3      8.82
4      2.94
5      1.47
6      5.88
7      1.47
8      4.41
9      1.47
10     1.47
12     1.47
13     4.41
Name: proportion, dtype: float64

In [39]:
import pandas as pd
import matplotlib.pyplot as plt

# Garantir que a coluna de data Ã© do tipo datetime
df['Carimbo de data/hora'] = pd.to_datetime(df['Carimbo de data/hora'])

# Criar coluna de mÃªs/ano para agrupamento
df['mes_ano'] = df['Carimbo de data/hora'].dt.strftime('%Y-%m')

# Criar tabela cruzada de severidade por mÃªs-ano
tabela_tempo = pd.crosstab(df['mes_ano'], df['Severidade'])

# Garantir que todos os meses entre o primeiro e o Ãºltimo registro apareÃ§am
primeiro_mes = df['Carimbo de data/hora'].min().strftime('%Y-%m')
ultimo_mes = df['Carimbo de data/hora'].max().strftime('%Y-%m')

# Criar um intervalo completo de meses
todos_meses = pd.date_range(
    start=primeiro_mes, 
    end=ultimo_mes, 
    freq='MS'
).strftime('%Y-%m').tolist()

# Reindexar para incluir todos os meses e preencher com zeros
tabela_tempo_completa = tabela_tempo.reindex(todos_meses, fill_value=0)

# Mostrar a tabela completa
print("TendÃªncias de severidade por mÃªs/ano:")
print(tabela_tempo_completa)

TendÃªncias de severidade por mÃªs/ano:
Severidade  Grave  Leve  Moderado  Sem adicÃ§Ã£o
mes_ano
2022-10         2     1         0            1
2022-11         0     3         1            3
2022-12         0     0         0            0
2023-01         2     0         0            0
2023-02         2     2         0            3
2023-03         1     0         0            0
2023-04         0     1         0            6
2023-05         4     2         0           10
2023-06         3     4         2           15

In [40]:

# Definir as possÃ­veis respostas
respostas = [0,
    1,
   2,
    3,
    4,
    5,
    6,
    7,
    
]

# Criar DataFrame para armazenar os percentuais
matriz_percentual = pd.DataFrame(index=perguntas, columns=respostas)

# Calcular percentuais para cada pergunta
for pergunta in perguntas:
    total_respostas = len(df[pergunta])
    distribuicao = df[pergunta].value_counts(normalize=True) * 100
    
    # Preencher matriz com os percentuais (colocando 0 onde nÃ£o hÃ¡ respostas)
    for resposta in respostas:
        if resposta in distribuicao:
            matriz_percentual.loc[pergunta, resposta] = distribuicao[resposta]
        else:
            matriz_percentual.loc[pergunta, resposta] = 0

# Substituir os nomes longos das perguntas por versÃµes mais curtas para melhor visualizaÃ§Ã£o
nomes_curtos = [f"Q{i+1}" for i in range(len(perguntas))]
matriz_percentual.index = nomes_curtos



# Arredondar para uma casa decimal para melhor visualizaÃ§Ã£o
matriz_formatada = matriz_percentual.round(1)

# Imprimir a matriz percentual
print("Matriz percentual de respostas por pergunta:")
matriz_formatada

Matriz percentual de respostas por pergunta:

,0,1,2,3,4,5,6,7
Q1,54.411765,11.764706,10.294118,5.882353,4.411765,7.352941,5.882353,0
Q2,25.0,22.058824,8.823529,22.058824,5.882353,5.882353,5.882353,4.411765
Q3,79.411765,8.823529,2.941176,2.941176,0,1.470588,4.411765,0
Q4,44.117647,11.764706,16.176471,7.352941,2.941176,2.941176,7.352941,7.352941
Q5,36.764706,14.705882,8.823529,8.823529,2.941176,8.823529,5.882353,13.235294
Q6,44.117647,7.352941,13.235294,7.352941,1.470588,4.411765,2.941176,19.117647
Q7,60.294118,8.823529,8.823529,1.470588,1.470588,5.882353,5.882353,7.352941
Q8,44.117647,14.705882,8.823529,5.882353,1.470588,5.882353,5.882353,13.235294
Q9,45.588235,13.235294,17.647059,5.882353,0,4.411765,8.823529,4.411765
Q10,64.705882,8.823529,4.411765,4.411765,2.941176,1.470588,10.294118,2.941176
Q11,38.235294,8.823529,13.235294,10.294118,2.941176,4.411765,8.823529,13.235294
Q12,77.941176,8.823529,2.941176,1.470588,0,2.941176,4.411765,1.470588
Q13,54.411765,5.882353,8.823529,4.411765,1.470588,2.941176,2.941176,19.117647

In [41]:
# Criar um DataFrame para armazenar os resultados
sintomas_por_pergunta = pd.DataFrame(index=range(1, len(perguntas)+1), columns=['Pergunta', 'Percentual SintomÃ¡tico'])


# Calcular o percentual sintomÃ¡tico para cada pergunta
for i, pergunta in enumerate(perguntas, 1):
    # Definir quais respostas sÃ£o consideradas sintomÃ¡ticas para esta pergunta
    if pergunta in itens_especiais:
        # Para perguntas especiais (1, 2, 4, 9, 10, 11), "Uma vez por semana" tambÃ©m conta
        indices_sintomaticos = [4, 5, 6, 7]  # Ãndices das colunas sintomÃ¡ticas na matriz formatada
    else:
        # Para as demais perguntas
        indices_sintomaticos = [5, 6, 7]  # Apenas frequÃªncias mais altas
    
    # Somar os percentuais das respostas sintomÃ¡ticas da linha correspondente
    percentual = matriz_formatada.iloc[i-1, indices_sintomaticos].sum()
    
    # Armazenar no DataFrame
    sintomas_por_pergunta.loc[i, 'Pergunta'] = f"Q{i}"
    sintomas_por_pergunta.loc[i, 'Percentual SintomÃ¡tico'] = percentual

# Ordenar do maior para o menor percentual
sintomas_por_pergunta = sintomas_por_pergunta.sort_values('Percentual SintomÃ¡tico', ascending=False)

# Apresentar o resultado
print("Percentual de respostas sintomÃ¡ticas por pergunta:")
print(sintomas_por_pergunta)

Percentual de respostas sintomÃ¡ticas por pergunta:
   Pergunta Percentual SintomÃ¡tico
11      Q11              29.411765
5        Q5              27.941176
6        Q6              26.470588
8        Q8                   25.0
13      Q13                   25.0
2        Q2              22.058824
4        Q4              20.588235
7        Q7              19.117647
1        Q1              17.647059
9        Q9              17.647059
10      Q10              17.647059
12      Q12               8.823529
3        Q3               5.882353